name: Update My AI List

on:
  push:
    branches:
      - main
  workflow_dispatch: # This adds a button so you can run it manually!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Get your files ready
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python (The language we are using)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Run your specific chores list
      - name: Run update script
        run: python update_list.py

      # 4. Save the changes back to your website
      - name: Save changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add index.md
          git commit -m "The robot updated the AI list!" || echo "No changes to commit"
          git push
